/**
 * Axovia CI/CD Dashboard Configuration
 * 
 * Monitors GitHub Actions across all ASPEN-managed projects
 */

const CONFIG = {
    // Projects to monitor
    projects: [
        {
            name: 'Docmind AI',
            owner: 'Axovia-AI',
            repo: 'docmind-ai',
            icon: '📄',
            description: 'AI-powered PDF editor'
        },
        {
            name: 'Flipper AI',
            owner: 'AXOVIA-ASPEN',
            repo: 'flipper-ai',
            icon: '🐧',
            description: 'Multi-marketplace flipping tool'
        },
        {
            name: 'Axovia Website',
            owner: 'Axovia-AI',
            repo: 'axovia-official-website',
            icon: '🌐',
            description: 'Official Axovia website'
        },
        {
            name: 'n8n Server',
            owner: 'AXOVIA-ASPEN',
            repo: 'n8n-server',
            icon: '🔄',
            description: 'Workflow automation server'
        },
        {
            name: 'Project Dashboard Template',
            owner: 'AXOVIA-ASPEN',
            repo: 'project-dashboard-template',
            icon: '📊',
            description: 'Reusable dashboard template'
        },
        {
            name: 'Real Random Portal',
            owner: 'AXOVIA-ASPEN',
            repo: 'real-random-dev-portal',
            icon: '🎲',
            description: 'Developer portal for Silverline Software'
        }
    ],

    // GitHub API configuration
    github: {
        apiUrl: 'https://api.github.com',
        // Token will be injected by GitHub Actions
        token: '{{GITHUB_TOKEN}}'
    },

    // Refresh interval (in seconds)
    refreshInterval: 60,

    // Data files (generated by GitHub Actions)
    dataFiles: {
        pipelines: 'data/pipelines.json',
        stats: 'data/stats.json',
        meta: 'data/meta.json'
    }
};

// Freeze config to prevent accidental modification
Object.freeze(CONFIG);
Object.freeze(CONFIG.github);
Object.freeze(CONFIG.dataFiles);
